default: &default
  # client can be of schemes : ipc, http or https
  client: "ipc://~/.ethereum/geth.ipc"
  #client: "https://minnie.freeftopia.org:8545"

development:
  <<: *default
  client: "http://5.196.23.94:8546"

test:
  <<: *default
  client: "http://localhost:8545"

production:
  <<: *default